server:
  port: 8089
  servlet:
    context-path: /user

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    password: Ikould09244313!
    driver-class-name: com.mysql.jdbc.Driver
    username: ikould

#mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.ikould.**.entity

